name: durak_server
description: WebSocket server for DTFool (Двойной переводной дурак)
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  durak_logic:
    path: ../logic
  durak_protocol:
    path: ../protocol
  sqlite3: ^2.4.0
  crypto: ^3.0.3
  hashlib: ^1.19.0
  mime: ^1.0.5

dev_dependencies:
  test: ^1.24.0
